// Auth types
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

// Category types
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';
export const CLEAR_CATEGORY_ERROR = 'CLEAR_CATEGORY_ERROR';

// Transaction types
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';
export const GET_TRANSACTION = 'GET_TRANSACTION';
export const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS';
export const GET_TRANSACTION_FAIL = 'GET_TRANSACTION_FAIL';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAIL = 'CREATE_TRANSACTION_FAIL';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FAIL = 'UPDATE_TRANSACTION_FAIL';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAIL = 'DELETE_TRANSACTION_FAIL';
export const CLEAR_TRANSACTION_ERROR = 'CLEAR_TRANSACTION_ERROR';

// Dashboard types
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
export const GET_DASHBOARD_DATA_SUCCESS = 'GET_DASHBOARD_DATA_SUCCESS';
export const GET_DASHBOARD_DATA_FAIL = 'GET_DASHBOARD_DATA_FAIL';
export const GET_EXPENSE_BREAKDOWN = 'GET_EXPENSE_BREAKDOWN';
export const GET_EXPENSE_BREAKDOWN_SUCCESS = 'GET_EXPENSE_BREAKDOWN_SUCCESS';
export const GET_EXPENSE_BREAKDOWN_FAIL = 'GET_EXPENSE_BREAKDOWN_FAIL';
export const GET_INCOME_BREAKDOWN = 'GET_INCOME_BREAKDOWN';
export const GET_INCOME_BREAKDOWN_SUCCESS = 'GET_INCOME_BREAKDOWN_SUCCESS';
export const GET_INCOME_BREAKDOWN_FAIL = 'GET_INCOME_BREAKDOWN_FAIL';
export const GET_TRANSACTION_TRENDS = 'GET_TRANSACTION_TRENDS';
export const GET_TRANSACTION_TRENDS_SUCCESS = 'GET_TRANSACTION_TRENDS_SUCCESS';
export const GET_TRANSACTION_TRENDS_FAIL = 'GET_TRANSACTION_TRENDS_FAIL';
export const CLEAR_DASHBOARD_ERROR = 'CLEAR_DASHBOARD_ERROR';

// Bill types
export const GET_BILLS = 'GET_BILLS';
export const GET_BILLS_SUCCESS = 'GET_BILLS_SUCCESS';
export const GET_BILLS_FAIL = 'GET_BILLS_FAIL';
export const GET_BILL = 'GET_BILL';
export const GET_BILL_SUCCESS = 'GET_BILL_SUCCESS';
export const GET_BILL_FAIL = 'GET_BILL_FAIL';
export const CREATE_BILL = 'CREATE_BILL';
export const CREATE_BILL_SUCCESS = 'CREATE_BILL_SUCCESS';
export const CREATE_BILL_FAIL = 'CREATE_BILL_FAIL';
export const UPDATE_BILL = 'UPDATE_BILL';
export const UPDATE_BILL_SUCCESS = 'UPDATE_BILL_SUCCESS';
export const UPDATE_BILL_FAIL = 'UPDATE_BILL_FAIL';
export const DELETE_BILL = 'DELETE_BILL';
export const DELETE_BILL_SUCCESS = 'DELETE_BILL_SUCCESS';
export const DELETE_BILL_FAIL = 'DELETE_BILL_FAIL';
export const MARK_BILL_PAID = 'MARK_BILL_PAID';
export const MARK_BILL_PAID_SUCCESS = 'MARK_BILL_PAID_SUCCESS';
export const MARK_BILL_PAID_FAIL = 'MARK_BILL_PAID_FAIL';
export const CLEAR_BILL_ERROR = 'CLEAR_BILL_ERROR';

// Savings Goal types
export const GET_SAVINGS_GOALS = 'GET_SAVINGS_GOALS';
export const GET_SAVINGS_GOALS_SUCCESS = 'GET_SAVINGS_GOALS_SUCCESS';
export const GET_SAVINGS_GOALS_FAIL = 'GET_SAVINGS_GOALS_FAIL';
export const GET_SAVINGS_GOAL = 'GET_SAVINGS_GOAL';
export const GET_SAVINGS_GOAL_SUCCESS = 'GET_SAVINGS_GOAL_SUCCESS';
export const GET_SAVINGS_GOAL_FAIL = 'GET_SAVINGS_GOAL_FAIL';
export const CREATE_SAVINGS_GOAL = 'CREATE_SAVINGS_GOAL';
export const CREATE_SAVINGS_GOAL_SUCCESS = 'CREATE_SAVINGS_GOAL_SUCCESS';
export const CREATE_SAVINGS_GOAL_FAIL = 'CREATE_SAVINGS_GOAL_FAIL';
export const UPDATE_SAVINGS_GOAL = 'UPDATE_SAVINGS_GOAL';
export const UPDATE_SAVINGS_GOAL_SUCCESS = 'UPDATE_SAVINGS_GOAL_SUCCESS';
export const UPDATE_SAVINGS_GOAL_FAIL = 'UPDATE_SAVINGS_GOAL_FAIL';
export const DELETE_SAVINGS_GOAL = 'DELETE_SAVINGS_GOAL';
export const DELETE_SAVINGS_GOAL_SUCCESS = 'DELETE_SAVINGS_GOAL_SUCCESS';
export const DELETE_SAVINGS_GOAL_FAIL = 'DELETE_SAVINGS_GOAL_FAIL';
export const ADD_CONTRIBUTION = 'ADD_CONTRIBUTION';
export const ADD_CONTRIBUTION_SUCCESS = 'ADD_CONTRIBUTION_SUCCESS';
export const ADD_CONTRIBUTION_FAIL = 'ADD_CONTRIBUTION_FAIL';
export const COMPLETE_SAVINGS_GOAL = 'COMPLETE_SAVINGS_GOAL';
export const COMPLETE_SAVINGS_GOAL_SUCCESS = 'COMPLETE_SAVINGS_GOAL_SUCCESS';
export const COMPLETE_SAVINGS_GOAL_FAIL = 'COMPLETE_SAVINGS_GOAL_FAIL';
export const CLEAR_SAVINGS_GOAL_ERROR = 'CLEAR_SAVINGS_GOAL_ERROR';

// Budget Template types
export const GET_BUDGET_TEMPLATES = 'GET_BUDGET_TEMPLATES';
export const GET_BUDGET_TEMPLATES_SUCCESS = 'GET_BUDGET_TEMPLATES_SUCCESS';
export const GET_BUDGET_TEMPLATES_FAIL = 'GET_BUDGET_TEMPLATES_FAIL';
export const GET_BUDGET_TEMPLATE = 'GET_BUDGET_TEMPLATE';
export const GET_BUDGET_TEMPLATE_SUCCESS = 'GET_BUDGET_TEMPLATE_SUCCESS';
export const GET_BUDGET_TEMPLATE_FAIL = 'GET_BUDGET_TEMPLATE_FAIL';
export const GET_DEFAULT_TEMPLATE = 'GET_DEFAULT_TEMPLATE';
export const GET_DEFAULT_TEMPLATE_SUCCESS = 'GET_DEFAULT_TEMPLATE_SUCCESS';
export const GET_DEFAULT_TEMPLATE_FAIL = 'GET_DEFAULT_TEMPLATE_FAIL';
export const CREATE_BUDGET_TEMPLATE = 'CREATE_BUDGET_TEMPLATE';
export const CREATE_BUDGET_TEMPLATE_SUCCESS = 'CREATE_BUDGET_TEMPLATE_SUCCESS';
export const CREATE_BUDGET_TEMPLATE_FAIL = 'CREATE_BUDGET_TEMPLATE_FAIL';
export const UPDATE_BUDGET_TEMPLATE = 'UPDATE_BUDGET_TEMPLATE';
export const UPDATE_BUDGET_TEMPLATE_SUCCESS = 'UPDATE_BUDGET_TEMPLATE_SUCCESS';
export const UPDATE_BUDGET_TEMPLATE_FAIL = 'UPDATE_BUDGET_TEMPLATE_FAIL';
export const DELETE_BUDGET_TEMPLATE = 'DELETE_BUDGET_TEMPLATE';
export const DELETE_BUDGET_TEMPLATE_SUCCESS = 'DELETE_BUDGET_TEMPLATE_SUCCESS';
export const DELETE_BUDGET_TEMPLATE_FAIL = 'DELETE_BUDGET_TEMPLATE_FAIL';
export const APPLY_BUDGET_TEMPLATE = 'APPLY_BUDGET_TEMPLATE';
export const APPLY_BUDGET_TEMPLATE_SUCCESS = 'APPLY_BUDGET_TEMPLATE_SUCCESS';
export const APPLY_BUDGET_TEMPLATE_FAIL = 'APPLY_BUDGET_TEMPLATE_FAIL';
export const CLEAR_BUDGET_TEMPLATE_ERROR = 'CLEAR_BUDGET_TEMPLATE_ERROR';

// Recurring Transaction types
export const GET_RECURRING_TRANSACTIONS = 'GET_RECURRING_TRANSACTIONS';
export const GET_RECURRING_TRANSACTIONS_SUCCESS = 'GET_RECURRING_TRANSACTIONS_SUCCESS';
export const GET_RECURRING_TRANSACTIONS_FAIL = 'GET_RECURRING_TRANSACTIONS_FAIL';
export const GET_RECURRING_TRANSACTION = 'GET_RECURRING_TRANSACTION';
export const GET_RECURRING_TRANSACTION_SUCCESS = 'GET_RECURRING_TRANSACTION_SUCCESS';
export const GET_RECURRING_TRANSACTION_FAIL = 'GET_RECURRING_TRANSACTION_FAIL';
export const CREATE_RECURRING_TRANSACTION = 'CREATE_RECURRING_TRANSACTION';
export const CREATE_RECURRING_TRANSACTION_SUCCESS = 'CREATE_RECURRING_TRANSACTION_SUCCESS';
export const CREATE_RECURRING_TRANSACTION_FAIL = 'CREATE_RECURRING_TRANSACTION_FAIL';
export const UPDATE_RECURRING_TRANSACTION = 'UPDATE_RECURRING_TRANSACTION';
export const UPDATE_RECURRING_TRANSACTION_SUCCESS = 'UPDATE_RECURRING_TRANSACTION_SUCCESS';
export const UPDATE_RECURRING_TRANSACTION_FAIL = 'UPDATE_RECURRING_TRANSACTION_FAIL';
export const DELETE_RECURRING_TRANSACTION = 'DELETE_RECURRING_TRANSACTION';
export const DELETE_RECURRING_TRANSACTION_SUCCESS = 'DELETE_RECURRING_TRANSACTION_SUCCESS';
export const DELETE_RECURRING_TRANSACTION_FAIL = 'DELETE_RECURRING_TRANSACTION_FAIL';
export const TOGGLE_RECURRING_TRANSACTION = 'TOGGLE_RECURRING_TRANSACTION';
export const TOGGLE_RECURRING_TRANSACTION_SUCCESS = 'TOGGLE_RECURRING_TRANSACTION_SUCCESS';
export const TOGGLE_RECURRING_TRANSACTION_FAIL = 'TOGGLE_RECURRING_TRANSACTION_FAIL';
export const GENERATE_TRANSACTIONS = 'GENERATE_TRANSACTIONS';
export const GENERATE_TRANSACTIONS_SUCCESS = 'GENERATE_TRANSACTIONS_SUCCESS';
export const GENERATE_TRANSACTIONS_FAIL = 'GENERATE_TRANSACTIONS_FAIL';
export const CLEAR_RECURRING_TRANSACTION_ERROR = 'CLEAR_RECURRING_TRANSACTION_ERROR';

// Analytics types
export const GET_SPENDING_TRENDS = 'GET_SPENDING_TRENDS';
export const GET_SPENDING_TRENDS_SUCCESS = 'GET_SPENDING_TRENDS_SUCCESS';
export const GET_SPENDING_TRENDS_FAIL = 'GET_SPENDING_TRENDS_FAIL';
export const GET_INCOME_VS_EXPENSE = 'GET_INCOME_VS_EXPENSE';
export const GET_INCOME_VS_EXPENSE_SUCCESS = 'GET_INCOME_VS_EXPENSE_SUCCESS';
export const GET_INCOME_VS_EXPENSE_FAIL = 'GET_INCOME_VS_EXPENSE_FAIL';
export const GET_BUDGET_VS_ACTUAL = 'GET_BUDGET_VS_ACTUAL';
export const GET_BUDGET_VS_ACTUAL_SUCCESS = 'GET_BUDGET_VS_ACTUAL_SUCCESS';
export const GET_BUDGET_VS_ACTUAL_FAIL = 'GET_BUDGET_VS_ACTUAL_FAIL';
export const GET_YEARLY_SUMMARY = 'GET_YEARLY_SUMMARY';
export const GET_YEARLY_SUMMARY_SUCCESS = 'GET_YEARLY_SUMMARY_SUCCESS';
export const GET_YEARLY_SUMMARY_FAIL = 'GET_YEARLY_SUMMARY_FAIL';
export const GET_FINANCIAL_INSIGHTS = 'GET_FINANCIAL_INSIGHTS';
export const GET_FINANCIAL_INSIGHTS_SUCCESS = 'GET_FINANCIAL_INSIGHTS_SUCCESS';
export const GET_FINANCIAL_INSIGHTS_FAIL = 'GET_FINANCIAL_INSIGHTS_FAIL';
export const GET_FINANCIAL_REPORT = 'GET_FINANCIAL_REPORT';
export const GET_FINANCIAL_REPORT_SUCCESS = 'GET_FINANCIAL_REPORT_SUCCESS';
export const GET_FINANCIAL_REPORT_FAIL = 'GET_FINANCIAL_REPORT_FAIL';
export const GET_FINANCIAL_HEALTH = 'GET_FINANCIAL_HEALTH';
export const GET_FINANCIAL_HEALTH_SUCCESS = 'GET_FINANCIAL_HEALTH_SUCCESS';
export const GET_FINANCIAL_HEALTH_FAIL = 'GET_FINANCIAL_HEALTH_FAIL';
export const CLEAR_ANALYTICS_ERROR = 'CLEAR_ANALYTICS_ERROR';

// Forecast types
export const GET_EXPENSE_FORECAST = 'GET_EXPENSE_FORECAST';
export const GET_EXPENSE_FORECAST_SUCCESS = 'GET_EXPENSE_FORECAST_SUCCESS';
export const GET_EXPENSE_FORECAST_FAIL = 'GET_EXPENSE_FORECAST_FAIL';
export const GET_CASHFLOW_PREDICTION = 'GET_CASHFLOW_PREDICTION';
export const GET_CASHFLOW_PREDICTION_SUCCESS = 'GET_CASHFLOW_PREDICTION_SUCCESS';
export const GET_CASHFLOW_PREDICTION_FAIL = 'GET_CASHFLOW_PREDICTION_FAIL';
export const CLEAR_FORECAST_ERROR = 'CLEAR_FORECAST_ERROR';