// Authentication types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Transaction types
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';
export const CLEAR_TRANSACTIONS = 'CLEAR_TRANSACTIONS';

// Category types
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES';
// Dashboard types
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR';

// Bill types
export const GET_BILLS = 'GET_BILLS';
export const GET_BILL = 'GET_BILL';
export const ADD_BILL = 'ADD_BILL';
export const UPDATE_BILL = 'UPDATE_BILL';
export const DELETE_BILL = 'DELETE_BILL';
export const MARK_BILL_PAID = 'MARK_BILL_PAID';
export const BILL_ERROR = 'BILL_ERROR';
export const CLEAR_BILLS = 'CLEAR_BILLS';
export const GET_UPCOMING_BILLS = 'GET_UPCOMING_BILLS';
export const GET_OVERDUE_BILLS = 'GET_OVERDUE_BILLS';

// Budget Template types
export const GET_BUDGET_TEMPLATES = 'GET_BUDGET_TEMPLATES';
export const GET_BUDGET_TEMPLATE = 'GET_BUDGET_TEMPLATE';
export const ADD_BUDGET_TEMPLATE = 'ADD_BUDGET_TEMPLATE';
export const UPDATE_BUDGET_TEMPLATE = 'UPDATE_BUDGET_TEMPLATE';
export const DELETE_BUDGET_TEMPLATE = 'DELETE_BUDGET_TEMPLATE';
export const GET_DEFAULT_TEMPLATE = 'GET_DEFAULT_TEMPLATE';
export const APPLY_TEMPLATE = 'APPLY_TEMPLATE';
export const TEMPLATE_ERROR = 'TEMPLATE_ERROR';
export const CLEAR_TEMPLATES = 'CLEAR_TEMPLATES';

// Savings Goal types
export const GET_SAVINGS_GOALS = 'GET_SAVINGS_GOALS';
export const GET_SAVINGS_GOAL = 'GET_SAVINGS_GOAL';
export const ADD_SAVINGS_GOAL = 'ADD_SAVINGS_GOAL';
export const UPDATE_SAVINGS_GOAL = 'UPDATE_SAVINGS_GOAL';
export const DELETE_SAVINGS_GOAL = 'DELETE_SAVINGS_GOAL';
export const ADD_CONTRIBUTION = 'ADD_CONTRIBUTION';
export const GET_SAVINGS_SUMMARY = 'GET_SAVINGS_SUMMARY';
export const SAVINGS_ERROR = 'SAVINGS_ERROR';
export const CLEAR_SAVINGS_GOALS = 'CLEAR_SAVINGS_GOALS';

// Alert types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';